services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - ollama-network
    restart: unless-stopped

networks:
  ollama-network:
    driver: bridge

volumes:
  ollama-data:
    name: ollama-data 